### ISSUE TITLE
could not download dataset zip?

### ISSUE THREAD

**Issue by leeQiao1995** [Junggy/HAMMER-dataset#1]
The zip is missing:http://www.campar.in.tum.de/public_datasets/2022_arxiv_jung/_dataset_processed.zip
error code is 301
pls fix 
thks

**Comment by Junggy** [comment]
Hi!

I heard there was little issue with the server.

Currnetly when I copy & paste the link into browser, it downloads well.

If theres any more issue, please let me know!
