### ISSUE TITLE
Definition of the polarization filter angles

### ISSUE THREAD

**Issue by Ikemura-kei** [Junggy/HAMMER-dataset#2]
Thank you for the great work! May I know more about the definition of the polarizer angles corresponding to each sub-image in the polarization images?

I suppose its the following order:

---------------
| 0    | 45   |
| 90  | 135 |
---------------

But I am not entirely sure, so clarification might be needed, thank you in advance.

**Comment by Junggy** [comment]
Thanks for your interest!
yes in theory we used clockwise order. When I use the camera again, I will check the script and let you know

**Comment by Ikemura-kei** [comment]
Thank you for your reply!

Just to make it clear, is clockwise by your definition the following?

---------------
| 0    | 45   |
|135 | 90   |
---------------

Which is a bit different from what we thought (see above).

**Comment by Junggy** [comment]
Ah sorry hahha actually
0 1
2 3
what you decribed early should be correct.
I used the wrong term !
