### ISSUE TITLE
Read Depth map

### ISSUE THREAD

**Issue by shenglunch** [Junggy/HAMMER-dataset#5]
How to read a metric depth map (meter)?

**Comment by Junggy** [comment]
thanks for your interest on our dataset!

reading depth is fairly simple.
its saved as 16 bit, and each value is mm. meaning that if the pixel value is 1000, it means 1000mm or 1m

if you use python opencv and want to read as meter, you can use

depth = cv2.imread(fname,-1).astype(np.uint16)/1000

if you have any questions, please let me know!

**Comment by shenglunch** [comment]
THX!
